config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'

  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :posts do
    member do
      post 'vote'
    end 
  	resources :comments, only: [:create]  do
      member do
        post 'vote'
      end
    end
  end

  resources :users, only: [:create]

  resources :categories, only: [:show, :new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :post_categories
	has_many :posts, through: :post_categories

	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	include Voteable
	
	belongs_to :post
	belongs_to :user

	has_many :votes, as: :voteable

	validates :comment_text, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
	include Voteable
	extend FriendlyId
  friendly_id :title, use: :slugged

	belongs_to :user

	has_many :post_categories
	has_many :categories, through: :post_categories

	has_many :comments

	has_many :votes, as: :voteable

	validates :title, presence: true
	validates :url, presence: true

end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
	belongs_to :post
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	extend FriendlyId
  friendly_id :username, use: :slugged

	has_many :posts
	has_many :comments

	has_many :votes, as: :voteable

	has_secure_password



	validates :username, presence: true, uniqueness: true
	validates :password, presence: true, on: :create
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
	belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?, :admin?

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in? 
  	!!current_user
  end

  def require_user
  	unless logged_in?
  		flash[:error] = 'You must be logged in to do that.'
  		redirect_to root_path
  	end
  end

  def require_admin
    unless admin?
      flash[:error] = 'You must be an admin to do that.'
      redirect_to root_path
    end
  end

  def admin?
    current_user.admin if current_user
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_filter :require_user, except: [:show]
	def new
		@category = Category.new
	end

	def create
		@category = Category.create(category_params)

		if @category.save
			redirect_to root_path, notice: 'Category has been created.'
		else
			render :new
		end

	end


	def show
		@category = Category.find(params[:id])
		@posts = @category.posts
	end

	private

	def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_filter :require_user 
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

  	if @comment.save
  		redirect_to post_path(@post), notice: "Comment was successfully created."
  	else #validation failure
  		render '/posts/show'
  	end
  end

  def vote
    @comment = Comment.find(params[:id])
    @comment.votes.create(vote: params[:vote], user: current_user)
    respond_to do |format|
      format.html do
        redirect_to :back, notice: "Your vote was counted."
      end
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text)
  end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

before_filter :find_post, only: [:show, :edit, :vote, :destroy]

before_filter :require_user, only: [:new, :edit, :create, :update]

before_filter :require_admin, only: [:destroy]

  def index
  	@posts = Post.all
  end

  def new
    @post=Post.new
    @categories_array = Category.all.map{ |category| [category.name, category.id]}
  end

  def create
  	@post = Post.create(post_params)
  	@post.user_id = current_user.id
  	if @post.save
  		redirect_to '/', notice: "Post was successfully created."
  	else #validation failure
      render :new
  	end
	end

	def show
		@comment = Comment.new
	end

  def edit

  end

  def destroy
    if @post.destroy
      redirect_to root_path, notice: "You successfully remove the post"
    end
  end

	def update 
		@post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_path(@post), notice: "You successfully updated your post."
    else #validation failure
      render :edit
    end
	end

  def vote
    @post.votes.create(vote: params[:vote], user: current_user)
    respond_to do |format|
      format.html do
        redirect_to :back, notice: "Your vote was counted."
      end
      format.js
    end
  end

  protected    
  
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :description, :category_ids =>[])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by_username(params[:username])

		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: 'Welcome, you have logged in.'
		else
			flash[:error] = 'There is something wrong with your username or password.'
			redirect_to login_path
		end

	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: 'You have logged out'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.create(user_params)

  	if @user.save
  		redirect_to '/', notice: "Your are registered."
  	else #validation failure
  		@user.errors.delete(:password_digest)
      render :new
  	end
	end
	
	private

	def user_params
		params.require(:user).permit(:username, :password)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def fix_url(str)
		str.start_with?("http://") ? str : "http://#{str}"
	end

	def display_datetime(dt)
		dt.strftime("%d/%m/%Y %H:%M")
	end

end

app/views/categories/new.html.erb
<%= render 'shared/errors', obj: @category %>


<%= form_for @category do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>
		<br/>
		<%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/categories/new.html.haml
= render 'shared/errors', obj: @category
= form_for @category do |f|
  = f.label :name
  = f.text_field :name
  %br/
  = f.submit class: "btn btn-primary"

app/views/categories/show.html.erb
<h4><%= link_to "All Posts", posts_path %> >> <%= @category.name %></h4>
<% @posts.each do |post| %>
		<div class="well span8">
			<p><%= link_to post.title, post.url %></p>
			<p><%= post.description %></p>
			<p>post by <%=post.user.username %></p>
			<br/>
			<p><%= link_to "#{post.comments.count} comments", post_path(post)%></p>
		</div>
	<% end %>

app/views/categories/show.html.haml
%h4
  = link_to "All Posts", posts_path
  >> #{@category.name}
- @posts.each do |post|
  .well.span8
    %p= link_to post.title, post.url
    %p= post.description
    %p
      post by #{post.user.username}
    %br/
    %p= link_to "#{post.comments.count} comments", post_path(post)

app/views/comments/vote.js.erb
$('#<%="comment_#{@comment.id}_id"%>').html("<%= @comment.total_votes %>")

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  <li>
    <%= link_to 'link', '' %>
  </li>
</ul>

	<div class='btn-group nav_item'>
		<%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
		Categories <span class='caret'></span>
		<% end %>
		<ul class='dropdown-menu'>
			<% Category.all.each do |category| %>
				<li>
					<%= link_to category.name, category_path(category) %>
				</li>
			<% end %>
			<% if logged_in? %>
				<li class='divider'></li>
				<li>
						<%= link_to(new_category_path) do %>
							<i class="icon-plus"></i>
							New Category
						<% end %>
				</li>
			<% end %>
		</ul>
	</div>

	<% if logged_in? %>
		<div class='nav_item'>
			<%= link_to "New Post", new_post_path, class: 'btn btn-success btn-small' %>
		</div>
		<div class='nav_item'>
			<%= link_to "Logout", logout_path, class: 'btn btn-small' %>
		</div>
	<% else #logged out %>
		<div class='nav_item'>
			<%= link_to "Register", register_path, class: 'btn btn-success btn-small' %>
		</div>
		<div class='nav_item'>
			<%= link_to "Login", login_path, class: 'btn btn-small' %>
		</div>
	<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/edit.html.erb
<h3>Edit post</h3>

<%= form_for @post do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>
		<br/>
		<%= f.label :url %>
		<%= f.text_field :url %>
		<br/>
		<%= f.label :description %>
		<%= f.text_area :description, rows: "3" %>
		<br/>
		<%= f.submit class: "btn btn-primary" %>

	<% end %>

app/views/posts/edit.html.haml
%h3 Edit post
= form_for @post do |f|
  = f.label :title
  = f.text_field :title
  %br/
  = f.label :url
  = f.text_field :url
  %br/
  = f.label :description
  = f.text_area :description, rows: "3"
  %br/
  = f.submit class: "btn btn-primary"

app/views/posts/index.html.erb
<%= render '/shared/content_lead', header: "All Posts" %>

<% @posts.each do |post| %>
	<div class="row">
		<div class="well span0 text-center" >
			<%= link_to vote_post_path(post, vote: true), remote: true, method: "post" do%>
				<i class="icon-arrow-up"></i>
			<% end %>
			<br/>
			<span id="<%="post_#{post.id}_id"%>"><%= post.total_votes %></span> votes
			<br/>
			<%= link_to vote_post_path(post, vote: false), remote: true, method: "post" do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		</div>
		<div class="well span8">
			<% post.categories.each do |category| %>
				<span class="label"> <%= link_to category.name, category_path(category.id) %> </span>
			<% end %>
			<p><%= link_to post.title, fix_url(post.url) %></p>
			<p><%= post.description %></p>
			<p>post by <%=post.user.username %> 
				<small> at <%= display_datetime(post.created_at) %> </small>
			</p>
			<br/>
			<p><%= link_to "#{post.comments.count} comments", post_path(post)%></p>
			<br/>
			<% if admin? %>
			<p><%= link_to post_path(post), method: "delete" do %>
				<i class='btn btn-danger'>Delete Post</i>
			<% end %>
			</p>
			<% end %>
		</div>
	</div>
	<% end %>

app/views/posts/new.html.erb
<h3>New post</h3>

<%= render 'shared/errors', obj: @post %>


<%= form_for @post do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>
		<br/>
		<%= f.label :url %>
		<%= f.text_field :url %>
		<br/>
		<%= f.label :description %>
		<%= f.text_area :description, rows: "3" %>
		<br/>
		<%= f.label :category_ids, "Categories" %>
		<%= f.collection_select(:category_ids, Category.all, :id, :name, {}, multiple: true) %>		
		
		<br/>
		<%= f.submit class: "btn btn-primary" %>

	<% end %>

app/views/posts/show.html.erb
<%= render '/shared/content_lead', header: (link_to @post.title, @post.url) %>
<p><%= @post.description %></p>
<hr>
<p></p>
	
<% if logged_in? %>
	<%= render 'shared/errors', obj: @comment %>

	<%= form_for [@post, @comment] do |f| %>
		<div class="control_group">
			<%= f.label :comment, "Leave a comment" %>
			<%= f.text_area :comment_text, rows: "3", class: "span4" %>
			<br/>
			<%= f.submit class: "btn btn-primary" %>
		</div>
	<% end %>
<% end %>
<hr>

<h6>Comments</h6>
<% @post.comments.each do |comment| %>
	<div class="row">
		<div class="well span0 text-center" >
			<%= link_to vote_post_comment_path(@post, comment, vote: true), remote: true, method: "post" do%>
				<i class="icon-arrow-up"></i>
			<% end %>
			<br/>
			<span id="<%="comment_#{comment.id}_id"%>"><%= comment.total_votes %></span> votes
			<br/>
			<%= link_to vote_post_comment_path(@post, comment, vote: false), remote: true, method: "post" do %>
				<i class="icon-arrow-down"></i>
			<% end %>
		</div>
		<div class="well span8">
			<em>
				<p>"<%= comment.comment_text %>"</p>
				<p>by <%= comment.user.username %> 
					<small> at <%= display_datetime(comment.created_at) %> </small>
				</p>
			</em>
		</div>
	</div>
<% end %>

app/views/posts/vote.js.erb
$('#<%="post_#{@post.id}_id"%>').html("<%= @post.total_votes %>")

app/views/shared/_content_lead.html.erb
<p class="lead">
	<%= header %></p>
<hr>
<p></p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="row">
		<div class="alert alert-error span 8">
			<h5>Please fix the following errors:</h5>
				<% obj.errors.full_messages.each do |msg| %>
					<ul>	
						<li> <%= msg %></li>
					</ul>
				<% end %>
		</div>
	</div>
<% end %>

app/views/users/new.html.erb
<h3>New users</h3>

<%= render 'shared/errors', obj: @user %>


<%= form_for @user do |f| %>

		<%= f.label :username %>
		<%= f.text_field :username %>
		<br/>
		<%= f.label :password %>
		<%= f.password_field :password %>
		<br/>
		<%= f.submit class: "btn btn-primary" %>

	<% end %>